pipeline {
    agent{
        label 'AGENT-1'
    }
    options{
        ansiColor('xterm')
    }

    // environment {
        
    // }

    stages {
        

        stage('Terraform Init and Plan') {
            steps {
                withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                    script {
                        sh """
                            cd 00-vpc
                            terraform init -reconfigure
                            terraform plan -out=tfplan
                        """ 
                    }
                }
            }
        }

        
    }

    post {
        always {
            deleteDir()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check logs for details.'
        }
    }
}
